const surprisePrompts: string[] = [
    "A majestic mountain range covered in snow",
    "A city skyline at night with vibrant colors",
    "A beautiful forest with a winding river",
    "A peaceful beach with crystal clear water",
    "A bustling market in a foreign city",
    "A mystical underwater world with sea creatures",
    "An enchanted forest with a magical tree",
    "A desert landscape with towering sand dunes",
    "An urban street filled with colorful graffiti art",
    "A futuristic city with flying cars and skyscrapers",
    "A serene countryside with rolling hills and fields of flowers",
    "A beautiful garden with a variety of colorful flowers",
    "A medieval castle on a hilltop",
    "A tropical island with palm trees and white sand beaches",
    "A magical winter wonderland with icicles and snowmen",
    "A tranquil lake surrounded by trees and mountains",
    "A steampunk city with intricate machinery",
    "A mysterious abandoned town with overgrown plants",
    "A majestic waterfall cascading down a cliff",
    "A whimsical candy land with gingerbread houses and candy trees",
    "A surreal cityscape with impossible architecture",
    "A serene Zen garden with a rock formation and a water feature",
    "A vintage amusement park with rides and games",
    "A post-apocalyptic wasteland with ruins and destruction",
    "A whimsical forest with mushrooms and fairies",
    "A futuristic space station orbiting a planet",
    "A creepy haunted house with ghosts and cobwebs",
    "A magical forest with fireflies and a rainbow sky",
    "A mystical mountain temple with a view of the valley",
    "An underwater city with coral reefs and exotic fish",
    "A peaceful village in a rural countryside",
    "A space colony on a distant planet",
    "A fairy tale castle with turrets and a moat",
    "A serene Japanese garden with a traditional tea house",
    "A steampunk airship floating in the clouds",
    "A bustling futuristic metropolis with flying cars and robots",
    "A creepy abandoned hospital with flickering lights",
    "A majestic statue in a city square",
    "A lush tropical rainforest with monkeys and birds",
    "A futuristic laboratory with high-tech equipment",
    "A futuristic city on the surface of Mars",
    "A serene mountain lake with reflections of the surrounding peaks",
    "An old European city with cobblestone streets and quaint buildings",
    "A whimsical underwater kingdom with mermaids and sea creatures",
    "A serene cottage by a river with a rustic wooden bridge",
    "A futuristic city in space with massive space stations and ships",
    "A creepy abandoned asylum with boarded-up windows",
    "A vibrant street festival with colorful decorations and performers",
    "A peaceful countryside with a barn and grazing cows",
    "A majestic ice palace with intricate snowflake patterns",
    "A futuristic cityscape with neon lights and holographic billboards",
    "A serene forest clearing with a babbling brook",
    "A mysterious pyramid in the desert",
    "A peaceful cabin in the woods with a fireplace",
    "A futuristic sports arena with high-tech equipment",
    "A whimsical candy forest with candy canes and gumdrops",
    "A serene river valley with a suspension bridge",
    "A creepy abandoned factory with rusted machinery",
    "A bustling street market in a foreign country",
    "A serene lake with a reflection of a mountain range",
    "A futuristic underwater research facility",
    "A medieval village with thatched-roof cottages and a castle",
]

export const generateRandomPrompts = (prompt:string): string => {
  const randomPromptIndex = Math.floor(Math.random() * surprisePrompts.length);
  const randomPrompt = surprisePrompts[randomPromptIndex];
   if(randomPrompt ===  prompt) return generateRandomPrompts(prompt)
  return randomPrompt
}